/* generated by pull.js */
const manifest = {
  "name": "HD Video Recorder Premium",
  "description": "Adds an ultra high-quality video recording button to the editor. Supports multiple resolutions (up to 4K), adjustable FPS, H.264/VP9 codec, and MP4 export for maximum compatibility.",
  "tags": [
    "recommended",
    "new"
  ],
  "info": [
    {
      "type": "notice",
      "text": "For best quality, use '1080p' or '4K' resolution with 'H.264' codec.",
      "id": "hqTip"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Resolution",
      "id": "resolution",
      "type": "select",
      "potentialValues": [
        {
          "id": "480p",
          "name": "480p (Standard)"
        },
        {
          "id": "720p",
          "name": "720p HD"
        },
        {
          "id": "1080p",
          "name": "1080p Full HD"
        },
        {
          "id": "1440p",
          "name": "1440p 2K"
        },
        {
          "id": "4k",
          "name": "4K Ultra HD"
        },
        {
          "id": "original",
          "name": "Original Stage Resolution"
        }
      ],
      "default": "1080p"
    },
    {
      "dynamic": true,
      "name": "FPS (Frames per second)",
      "id": "fps",
      "type": "select",
      "potentialValues": [
        {
          "id": "24",
          "name": "24 fps (Cinematic)"
        },
        {
          "id": "30",
          "name": "30 fps (Standard)"
        },
        {
          "id": "60",
          "name": "60 fps (Smooth)"
        },
        {
          "id": "120",
          "name": "120 fps (Ultra Smooth)"
        }
      ],
      "default": "60"
    },
    {
      "dynamic": true,
      "name": "Video Codec",
      "id": "codec",
      "type": "select",
      "potentialValues": [
        {
          "id": "h264",
          "name": "H.264 (Best Compatibility)"
        },
        {
          "id": "vp9",
          "name": "VP9 (Best Quality)"
        },
        {
          "id": "av1",
          "name": "AV1 (Most Efficient)"
        }
      ],
      "default": "h264"
    },
    {
      "dynamic": true,
      "name": "Output Format",
      "id": "outputFormat",
      "type": "select",
      "potentialValues": [
        {
          "id": "mp4",
          "name": "MP4 (Recommended)"
        },
        {
          "id": "webm",
          "name": "WebM (Alternative)"
        }
      ],
      "default": "mp4"
    },
    {
      "dynamic": true,
      "name": "Video Bitrate",
      "id": "bitrate",
      "type": "select",
      "potentialValues": [
        {
          "id": "low",
          "name": "Low (2 Mbps)"
        },
        {
          "id": "medium",
          "name": "Medium (5 Mbps)"
        },
        {
          "id": "high",
          "name": "High (10 Mbps)"
        },
        {
          "id": "ultra",
          "name": "Ultra (20 Mbps - Maximum Quality)"
        },
        {
          "id": "max",
          "name": "Maximum (50 Mbps)"
        }
      ],
      "default": "ultra"
    },
    {
      "dynamic": true,
      "name": "Record Project Audio",
      "id": "includeProjectAudio",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Record Microphone",
      "id": "includeMic",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Auto-convert WebM to MP4",
      "id": "autoConvertToMp4",
      "type": "boolean",
      "default": true
    }
  ],
  "enabledByDefault": false
};
import {mediaRecorderSupported} from "../../environment";
if (!mediaRecorderSupported) manifest.unsupported = true;
export default manifest;
