/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "HD Image Upload Premium",
  "description": "Adds an ultra high-quality image upload button. Supports smart resizing, maintains original quality, and allows choosing between SVG vector or PNG/WebP in high resolution.",
  "tags": [
    "beta",
    "new"
  ],
  "info": [
    {
      "type": "notice",
      "text": "Avoid using the HD button if you plan to edit the image after uploading.",
      "id": "notSuitableEdit"
    },
    {
      "type": "notice",
      "text": "For maximum quality, use 'Keep Original' or 'SVG Vector' options.",
      "id": "maxQualityTip"
    }
  ],
  "credits": [
    {
      "name": "ErrorGamer2000",
      "link": "https://scratch.mit.edu/users/ErrorGamer2000/"
    },
    {
      "name": "GarboMuffin"
    },
    {
      "name": "World_Languages"
    },
    {
      "name": "SheepTester",
      "link": "https://scratch.mit.edu/users/Sheep_maker/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Image Size",
      "id": "fitting",
      "type": "select",
      "potentialValues": [
        {
          "id": "original",
          "name": "Keep Original (Maximum Quality)"
        },
        {
          "id": "full",
          "name": "Full Original Size"
        },
        {
          "id": "fit",
          "name": "Shrink to Fit Stage"
        },
        {
          "id": "fill",
          "name": "Stretch to Fill Stage"
        },
        {
          "id": "2x",
          "name": "2x Stage Resolution"
        },
        {
          "id": "4x",
          "name": "4x Stage Resolution"
        }
      ],
      "default": "original"
    },
    {
      "dynamic": true,
      "name": "Output Format",
      "id": "outputFormat",
      "type": "select",
      "potentialValues": [
        {
          "id": "svg",
          "name": "SVG (Vector - Best Quality)"
        },
        {
          "id": "png",
          "name": "PNG (High Quality)"
        },
        {
          "id": "webp",
          "name": "WebP (Best Compression)"
        }
      ],
      "default": "svg"
    },
    {
      "dynamic": true,
      "name": "PNG/WebP Quality",
      "id": "quality",
      "type": "select",
      "potentialValues": [
        {
          "id": "100",
          "name": "100% (Lossless)"
        },
        {
          "id": "95",
          "name": "95%"
        },
        {
          "id": "90",
          "name": "90%"
        }
      ],
      "default": "100"
    },
    {
      "dynamic": true,
      "name": "Image Smoothing",
      "id": "smoothing",
      "type": "boolean",
      "default": true
    }
  ]
};
export default manifest;
